# Generated by Django 5.0.6 on 2024-07-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canbanBackend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subtasks',
        ),
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.ManyToManyField(blank=True, to='canbanBackend.subtask'),
        ),
    ]
