# Generated by Django 5.0.6 on 2024-07-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canbanBackend', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='canbanBackend.contact'),
        ),
    ]
